%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'credit_NK';
M_.dynare_version = '5.4';
oo_.dynare_version = '5.4';
options_.dynare_version = '5.4';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(10,1);
M_.exo_names_tex = cell(10,1);
M_.exo_names_long = cell(10,1);
M_.exo_names(1) = {'eta_a'};
M_.exo_names_tex(1) = {'eta\_a'};
M_.exo_names_long(1) = {'eta_a'};
M_.exo_names(2) = {'eta_g'};
M_.exo_names_tex(2) = {'eta\_g'};
M_.exo_names_long(2) = {'eta_g'};
M_.exo_names(3) = {'eta_c'};
M_.exo_names_tex(3) = {'eta\_c'};
M_.exo_names_long(3) = {'eta_c'};
M_.exo_names(4) = {'eta_m'};
M_.exo_names_tex(4) = {'eta\_m'};
M_.exo_names_long(4) = {'eta_m'};
M_.exo_names(5) = {'eta_i'};
M_.exo_names_tex(5) = {'eta\_i'};
M_.exo_names_long(5) = {'eta_i'};
M_.exo_names(6) = {'eta_r'};
M_.exo_names_tex(6) = {'eta\_r'};
M_.exo_names_long(6) = {'eta_r'};
M_.exo_names(7) = {'eta_t'};
M_.exo_names_tex(7) = {'eta\_t'};
M_.exo_names_long(7) = {'eta_t'};
M_.exo_names(8) = {'eta_p'};
M_.exo_names_tex(8) = {'eta\_p'};
M_.exo_names_long(8) = {'eta_p'};
M_.exo_names(9) = {'eta_o'};
M_.exo_names_tex(9) = {'eta\_o'};
M_.exo_names_long(9) = {'eta_o'};
M_.exo_names(10) = {'eta_s'};
M_.exo_names_tex(10) = {'eta\_s'};
M_.exo_names_long(10) = {'eta_s'};
M_.endo_names = cell(44,1);
M_.endo_names_tex = cell(44,1);
M_.endo_names_long = cell(44,1);
M_.endo_names(1) = {'rr'};
M_.endo_names_tex(1) = {'rr'};
M_.endo_names_long(1) = {'rr'};
M_.endo_names(2) = {'c'};
M_.endo_names_tex(2) = {'c'};
M_.endo_names_long(2) = {'c'};
M_.endo_names(3) = {'c_E'};
M_.endo_names_tex(3) = {'c\_E'};
M_.endo_names_long(3) = {'c_E'};
M_.endo_names(4) = {'c_H'};
M_.endo_names_tex(4) = {'c\_H'};
M_.endo_names_long(4) = {'c_H'};
M_.endo_names(5) = {'h'};
M_.endo_names_tex(5) = {'h'};
M_.endo_names_long(5) = {'h'};
M_.endo_names(6) = {'w'};
M_.endo_names_tex(6) = {'w'};
M_.endo_names_long(6) = {'w'};
M_.endo_names(7) = {'y'};
M_.endo_names_tex(7) = {'y'};
M_.endo_names_long(7) = {'y'};
M_.endo_names(8) = {'k'};
M_.endo_names_tex(8) = {'k'};
M_.endo_names_long(8) = {'k'};
M_.endo_names(9) = {'i'};
M_.endo_names_tex(9) = {'i'};
M_.endo_names_long(9) = {'i'};
M_.endo_names(10) = {'l'};
M_.endo_names_tex(10) = {'l'};
M_.endo_names_long(10) = {'l'};
M_.endo_names(11) = {'lb_E'};
M_.endo_names_tex(11) = {'lb\_E'};
M_.endo_names_long(11) = {'lb_E'};
M_.endo_names(12) = {'phi_E'};
M_.endo_names_tex(12) = {'phi\_E'};
M_.endo_names_long(12) = {'phi_E'};
M_.endo_names(13) = {'mc'};
M_.endo_names_tex(13) = {'mc'};
M_.endo_names_long(13) = {'mc'};
M_.endo_names(14) = {'pi'};
M_.endo_names_tex(14) = {'pi'};
M_.endo_names_long(14) = {'pi'};
M_.endo_names(15) = {'r'};
M_.endo_names_tex(15) = {'r'};
M_.endo_names_long(15) = {'r'};
M_.endo_names(16) = {'lb_H'};
M_.endo_names_tex(16) = {'lb\_H'};
M_.endo_names_long(16) = {'lb_H'};
M_.endo_names(17) = {'q'};
M_.endo_names_tex(17) = {'q'};
M_.endo_names_long(17) = {'q'};
M_.endo_names(18) = {'varrho'};
M_.endo_names_tex(18) = {'varrho'};
M_.endo_names_long(18) = {'varrho'};
M_.endo_names(19) = {'tau'};
M_.endo_names_tex(19) = {'tau'};
M_.endo_names_long(19) = {'tau'};
M_.endo_names(20) = {'mu'};
M_.endo_names_tex(20) = {'mu'};
M_.endo_names_long(20) = {'mu'};
M_.endo_names(21) = {'e'};
M_.endo_names_tex(21) = {'e'};
M_.endo_names_long(21) = {'e'};
M_.endo_names(22) = {'g'};
M_.endo_names_tex(22) = {'g'};
M_.endo_names_long(22) = {'g'};
M_.endo_names(23) = {'gy_obs'};
M_.endo_names_tex(23) = {'gy\_obs'};
M_.endo_names_long(23) = {'gy_obs'};
M_.endo_names(24) = {'gc_obs'};
M_.endo_names_tex(24) = {'gc\_obs'};
M_.endo_names_long(24) = {'gc_obs'};
M_.endo_names(25) = {'gi_obs'};
M_.endo_names_tex(25) = {'gi\_obs'};
M_.endo_names_long(25) = {'gi_obs'};
M_.endo_names(26) = {'pi_obs'};
M_.endo_names_tex(26) = {'pi\_obs'};
M_.endo_names_long(26) = {'pi_obs'};
M_.endo_names(27) = {'r_obs'};
M_.endo_names_tex(27) = {'r\_obs'};
M_.endo_names_long(27) = {'r_obs'};
M_.endo_names(28) = {'l_obs'};
M_.endo_names_tex(28) = {'l\_obs'};
M_.endo_names_long(28) = {'l_obs'};
M_.endo_names(29) = {'b_s'};
M_.endo_names_tex(29) = {'b\_s'};
M_.endo_names_long(29) = {'b_s'};
M_.endo_names(30) = {'b_o'};
M_.endo_names_tex(30) = {'b\_o'};
M_.endo_names_long(30) = {'b_o'};
M_.endo_names(31) = {'b_s_E'};
M_.endo_names_tex(31) = {'b\_s\_E'};
M_.endo_names_long(31) = {'b_s_E'};
M_.endo_names(32) = {'b_o_E'};
M_.endo_names_tex(32) = {'b\_o\_E'};
M_.endo_names_long(32) = {'b_o_E'};
M_.endo_names(33) = {'r_s'};
M_.endo_names_tex(33) = {'r\_s'};
M_.endo_names_long(33) = {'r_s'};
M_.endo_names(34) = {'r_o'};
M_.endo_names_tex(34) = {'r\_o'};
M_.endo_names_long(34) = {'r_o'};
M_.endo_names(35) = {'e_a'};
M_.endo_names_tex(35) = {'e\_a'};
M_.endo_names_long(35) = {'e_a'};
M_.endo_names(36) = {'e_g'};
M_.endo_names_tex(36) = {'e\_g'};
M_.endo_names_long(36) = {'e_g'};
M_.endo_names(37) = {'e_c'};
M_.endo_names_tex(37) = {'e\_c'};
M_.endo_names_long(37) = {'e_c'};
M_.endo_names(38) = {'e_m'};
M_.endo_names_tex(38) = {'e\_m'};
M_.endo_names_long(38) = {'e_m'};
M_.endo_names(39) = {'e_i'};
M_.endo_names_tex(39) = {'e\_i'};
M_.endo_names_long(39) = {'e_i'};
M_.endo_names(40) = {'e_r'};
M_.endo_names_tex(40) = {'e\_r'};
M_.endo_names_long(40) = {'e_r'};
M_.endo_names(41) = {'e_t'};
M_.endo_names_tex(41) = {'e\_t'};
M_.endo_names_long(41) = {'e_t'};
M_.endo_names(42) = {'e_p'};
M_.endo_names_tex(42) = {'e\_p'};
M_.endo_names_long(42) = {'e_p'};
M_.endo_names(43) = {'e_s'};
M_.endo_names_tex(43) = {'e\_s'};
M_.endo_names_long(43) = {'e_s'};
M_.endo_names(44) = {'e_o'};
M_.endo_names_tex(44) = {'e\_o'};
M_.endo_names_long(44) = {'e_o'};
M_.endo_partitions = struct();
M_.param_names = cell(40,1);
M_.param_names_tex = cell(40,1);
M_.param_names_long = cell(40,1);
M_.param_names(1) = {'beta_E'};
M_.param_names_tex(1) = {'beta\_E'};
M_.param_names_long(1) = {'beta_E'};
M_.param_names(2) = {'beta_H'};
M_.param_names_tex(2) = {'beta\_H'};
M_.param_names_long(2) = {'beta_H'};
M_.param_names(3) = {'delta'};
M_.param_names_tex(3) = {'delta'};
M_.param_names_long(3) = {'delta'};
M_.param_names(4) = {'alpha'};
M_.param_names_tex(4) = {'alpha'};
M_.param_names_long(4) = {'alpha'};
M_.param_names(5) = {'sigmaC'};
M_.param_names_tex(5) = {'sigmaC'};
M_.param_names_long(5) = {'sigmaC'};
M_.param_names(6) = {'sigmaL'};
M_.param_names_tex(6) = {'sigmaL'};
M_.param_names_long(6) = {'sigmaL'};
M_.param_names(7) = {'chi_l'};
M_.param_names_tex(7) = {'chi\_l'};
M_.param_names_long(7) = {'chi_l'};
M_.param_names(8) = {'gy'};
M_.param_names_tex(8) = {'gy'};
M_.param_names_long(8) = {'gy'};
M_.param_names(9) = {'A'};
M_.param_names_tex(9) = {'A'};
M_.param_names_long(9) = {'A'};
M_.param_names(10) = {'mh'};
M_.param_names_tex(10) = {'mh'};
M_.param_names_long(10) = {'mh'};
M_.param_names(11) = {'mk'};
M_.param_names_tex(11) = {'mk'};
M_.param_names_long(11) = {'mk'};
M_.param_names(12) = {'hh'};
M_.param_names_tex(12) = {'hh'};
M_.param_names_long(12) = {'hh'};
M_.param_names(13) = {'epsilon'};
M_.param_names_tex(13) = {'epsilon'};
M_.param_names_long(13) = {'epsilon'};
M_.param_names(14) = {'kappa'};
M_.param_names_tex(14) = {'kappa'};
M_.param_names_long(14) = {'kappa'};
M_.param_names(15) = {'rho'};
M_.param_names_tex(15) = {'rho'};
M_.param_names_long(15) = {'rho'};
M_.param_names(16) = {'phi_y'};
M_.param_names_tex(16) = {'phi\_y'};
M_.param_names_long(16) = {'phi_y'};
M_.param_names(17) = {'phi_pi'};
M_.param_names_tex(17) = {'phi\_pi'};
M_.param_names_long(17) = {'phi_pi'};
M_.param_names(18) = {'psi'};
M_.param_names_tex(18) = {'psi'};
M_.param_names_long(18) = {'psi'};
M_.param_names(19) = {'piss'};
M_.param_names_tex(19) = {'piss'};
M_.param_names_long(19) = {'piss'};
M_.param_names(20) = {'rho_a'};
M_.param_names_tex(20) = {'rho\_a'};
M_.param_names_long(20) = {'rho_a'};
M_.param_names(21) = {'rho_g'};
M_.param_names_tex(21) = {'rho\_g'};
M_.param_names_long(21) = {'rho_g'};
M_.param_names(22) = {'rho_c'};
M_.param_names_tex(22) = {'rho\_c'};
M_.param_names_long(22) = {'rho_c'};
M_.param_names(23) = {'rho_m'};
M_.param_names_tex(23) = {'rho\_m'};
M_.param_names_long(23) = {'rho_m'};
M_.param_names(24) = {'rho_i'};
M_.param_names_tex(24) = {'rho\_i'};
M_.param_names_long(24) = {'rho_i'};
M_.param_names(25) = {'rho_r'};
M_.param_names_tex(25) = {'rho\_r'};
M_.param_names_long(25) = {'rho_r'};
M_.param_names(26) = {'rho_t'};
M_.param_names_tex(26) = {'rho\_t'};
M_.param_names_long(26) = {'rho_t'};
M_.param_names(27) = {'rho_p'};
M_.param_names_tex(27) = {'rho\_p'};
M_.param_names_long(27) = {'rho_p'};
M_.param_names(28) = {'sig'};
M_.param_names_tex(28) = {'sig'};
M_.param_names_long(28) = {'sig'};
M_.param_names(29) = {'theta1'};
M_.param_names_tex(29) = {'theta1'};
M_.param_names_long(29) = {'theta1'};
M_.param_names(30) = {'theta2'};
M_.param_names_tex(30) = {'theta2'};
M_.param_names_long(30) = {'theta2'};
M_.param_names(31) = {'varphi'};
M_.param_names_tex(31) = {'varphi'};
M_.param_names_long(31) = {'varphi'};
M_.param_names(32) = {'tau0'};
M_.param_names_tex(32) = {'tau0'};
M_.param_names_long(32) = {'tau0'};
M_.param_names(33) = {'y0'};
M_.param_names_tex(33) = {'y0'};
M_.param_names_long(33) = {'y0'};
M_.param_names(34) = {'chi_s'};
M_.param_names_tex(34) = {'chi\_s'};
M_.param_names_long(34) = {'chi_s'};
M_.param_names(35) = {'chi_o'};
M_.param_names_tex(35) = {'chi\_o'};
M_.param_names_long(35) = {'chi_o'};
M_.param_names(36) = {'sigmaS'};
M_.param_names_tex(36) = {'sigmaS'};
M_.param_names_long(36) = {'sigmaS'};
M_.param_names(37) = {'sigmaO'};
M_.param_names_tex(37) = {'sigmaO'};
M_.param_names_long(37) = {'sigmaO'};
M_.param_names(38) = {'rho_s'};
M_.param_names_tex(38) = {'rho\_s'};
M_.param_names_long(38) = {'rho_s'};
M_.param_names(39) = {'rho_o'};
M_.param_names_tex(39) = {'rho\_o'};
M_.param_names_long(39) = {'rho_o'};
M_.param_names(40) = {'BDratio'};
M_.param_names_tex(40) = {'BDratio'};
M_.param_names_long(40) = {'BDratio'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 10;
M_.endo_nbr = 44;
M_.param_nbr = 40;
M_.orig_endo_nbr = 44;
M_.aux_vars = [];
options_.varobs = cell(6, 1);
options_.varobs(1)  = {'gy_obs'};
options_.varobs(2)  = {'pi_obs'};
options_.varobs(3)  = {'r_obs'};
options_.varobs(4)  = {'gc_obs'};
options_.varobs(5)  = {'gi_obs'};
options_.varobs(6)  = {'l_obs'};
options_.varobs_id = [ 23 26 27 24 25 28  ];
M_ = setup_solvers(M_);
M_.Sigma_e = zeros(10, 10);
M_.Correlation_matrix = eye(10, 10);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
options_.linear = false;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
M_.orig_eq_nbr = 44;
M_.eq_nbr = 44;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 0 21 0;
 1 22 0;
 2 23 0;
 3 24 0;
 0 25 0;
 0 26 0;
 4 27 65;
 5 28 0;
 6 29 66;
 7 30 0;
 0 31 67;
 0 32 0;
 0 33 0;
 0 34 68;
 8 35 0;
 0 36 69;
 0 37 70;
 0 38 71;
 0 39 0;
 0 40 0;
 0 41 0;
 0 42 0;
 0 43 0;
 0 44 0;
 0 45 0;
 0 46 0;
 0 47 0;
 0 48 0;
 9 49 0;
 10 50 0;
 0 51 0;
 0 52 0;
 0 53 72;
 0 54 73;
 11 55 0;
 12 56 0;
 13 57 0;
 14 58 0;
 15 59 74;
 16 60 0;
 17 61 0;
 18 62 0;
 19 63 0;
 20 64 0;]';
M_.nstatic = 17;
M_.nfwrd   = 7;
M_.npred   = 17;
M_.nboth   = 3;
M_.nsfwrd   = 10;
M_.nspred   = 20;
M_.ndynamic   = 27;
M_.dynamic_tmp_nbr = [28; 9; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , 'marginal utility of consumption' ;
  2 , 'name' , 'Euler' ;
  3 , 'name' , 'Labor Supply' ;
  4 , 'name' , 'FOC i' ;
  5 , 'name' , 'Euler ordinary bonds (b_o)' ;
  6 , 'name' , 'Euler SLBs (b_s)' ;
  7 , 'name' , 'technology' ;
  8 , 'name' , 'Borrowing constraint' ;
  9 , 'name' , 'Capital law of motion' ;
  10 , 'name' , 'FOC c' ;
  11 , 'name' , 'FOC l' ;
  12 , 'name' , 'FOC k' ;
  13 , 'name' , 'FOC h' ;
  14 , 'name' , 'NKPC' ;
  15 , 'name' , 'FOC y' ;
  16 , 'name' , 'FOC mu' ;
  17 , 'name' , 'balance sheet' ;
  18 , 'name' , 'Ordinary bond market clearing condition' ;
  19 , 'name' , 'SLB market clearing condition' ;
  20 , 'name' , 'Firms debt structure' ;
  21 , 'name' , 'Firms capital structure' ;
  22 , 'name' , 'Resources Constraint' ;
  23 , 'name' , 'Total consumption' ;
  24 , 'name' , 'Total emissions' ;
  25 , 'name' , 'Fisherian equation' ;
  26 , 'name' , 'Monetary Policy rule' ;
  27 , 'name' , 'Public spending' ;
  28 , 'name' , 'Carbon tax' ;
  29 , 'name' , 'measurement GDP' ;
  30 , 'name' , 'measurement consumption' ;
  31 , 'name' , 'measurement investment' ;
  32 , 'name' , 'measurement inflation' ;
  33 , 'name' , 'measurement interest rate' ;
  34 , 'name' , 'measurement corporate loans' ;
  35 , 'name' , 'shocks' ;
  36 , 'name' , '36' ;
  37 , 'name' , '37' ;
  38 , 'name' , '38' ;
  39 , 'name' , '39' ;
  40 , 'name' , '40' ;
  41 , 'name' , '41' ;
  42 , 'name' , '42' ;
  43 , 'name' , '43' ;
  44 , 'name' , '44' ;
};
M_.mapping.rr.eqidx = [2 8 11 12 25 ];
M_.mapping.c.eqidx = [22 23 30 ];
M_.mapping.c_E.eqidx = [10 17 23 ];
M_.mapping.c_H.eqidx = [1 23 ];
M_.mapping.h.eqidx = [3 7 8 13 17 ];
M_.mapping.w.eqidx = [3 8 13 17 ];
M_.mapping.y.eqidx = [7 12 13 14 15 16 17 22 24 26 27 29 ];
M_.mapping.k.eqidx = [7 8 9 12 21 ];
M_.mapping.i.eqidx = [4 9 17 22 31 ];
M_.mapping.l.eqidx = [8 17 20 21 34 ];
M_.mapping.lb_E.eqidx = [4 10 11 14 ];
M_.mapping.phi_E.eqidx = [11 12 13 ];
M_.mapping.mc.eqidx = [14 15 17 ];
M_.mapping.pi.eqidx = [5 6 14 17 22 25 26 32 ];
M_.mapping.r.eqidx = [17 25 26 33 ];
M_.mapping.lb_H.eqidx = [1 2 3 5 6 ];
M_.mapping.q.eqidx = [4 8 12 ];
M_.mapping.varrho.eqidx = [12 13 15 ];
M_.mapping.tau.eqidx = [15 16 17 28 ];
M_.mapping.mu.eqidx = [15 16 17 22 24 ];
M_.mapping.e.eqidx = [17 24 ];
M_.mapping.g.eqidx = [22 27 ];
M_.mapping.gy_obs.eqidx = [29 ];
M_.mapping.gc_obs.eqidx = [30 ];
M_.mapping.gi_obs.eqidx = [31 ];
M_.mapping.pi_obs.eqidx = [32 ];
M_.mapping.r_obs.eqidx = [33 ];
M_.mapping.l_obs.eqidx = [34 ];
M_.mapping.b_s.eqidx = [6 17 19 ];
M_.mapping.b_o.eqidx = [5 17 18 ];
M_.mapping.b_s_E.eqidx = [17 19 20 21 ];
M_.mapping.b_o_E.eqidx = [17 18 20 21 ];
M_.mapping.r_s.eqidx = [6 17 ];
M_.mapping.r_o.eqidx = [5 17 ];
M_.mapping.e_a.eqidx = [7 35 ];
M_.mapping.e_g.eqidx = [27 36 ];
M_.mapping.e_c.eqidx = [1 10 37 ];
M_.mapping.e_m.eqidx = [8 12 40 ];
M_.mapping.e_i.eqidx = [4 9 39 ];
M_.mapping.e_r.eqidx = [26 41 ];
M_.mapping.e_t.eqidx = [28 42 ];
M_.mapping.e_p.eqidx = [38 ];
M_.mapping.e_s.eqidx = [6 44 ];
M_.mapping.e_o.eqidx = [5 43 ];
M_.mapping.eta_a.eqidx = [35 ];
M_.mapping.eta_g.eqidx = [36 ];
M_.mapping.eta_c.eqidx = [37 ];
M_.mapping.eta_m.eqidx = [40 ];
M_.mapping.eta_i.eqidx = [39 ];
M_.mapping.eta_r.eqidx = [41 ];
M_.mapping.eta_t.eqidx = [42 ];
M_.mapping.eta_p.eqidx = [38 ];
M_.mapping.eta_o.eqidx = [43 ];
M_.mapping.eta_s.eqidx = [44 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [2 3 4 7 8 9 10 15 29 30 35 36 37 38 39 40 41 42 43 44 ];
M_.exo_names_orig_ord = [1:10];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(44, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(10, 1);
M_.params = NaN(40, 1);
M_.endo_trends = struct('deflator', cell(44, 1), 'log_deflator', cell(44, 1), 'growth_factor', cell(44, 1), 'log_growth_factor', cell(44, 1));
M_.NNZDerivatives = [184; -1; -1; ];
M_.static_tmp_nbr = [17; 7; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
close all;
M_.params(2) = 0.993;
beta_H = M_.params(2);
M_.params(1) = 0.980;
beta_E = M_.params(1);
M_.params(3) = 0.025;
delta = M_.params(3);
M_.params(4) = 0.30;
alpha = M_.params(4);
M_.params(8) = 0.2;
gy = M_.params(8);
M_.params(12) = 0.7;
hh = M_.params(12);
M_.params(5) = 1;
sigmaC = M_.params(5);
M_.params(6) = 1;
sigmaL = M_.params(6);
M_.params(11) = 0.8;
mk = M_.params(11);
M_.params(10) = 0.1;
mh = M_.params(10);
M_.params(13) = 10;
epsilon = M_.params(13);
M_.params(15) = .8;
rho = M_.params(15);
M_.params(16) = 0;
phi_y = M_.params(16);
M_.params(17) = 1.5;
phi_pi = M_.params(17);
M_.params(18) = 80;
psi = M_.params(18);
M_.params(14) = 4;
kappa = M_.params(14);
M_.params(31) = 0.2;
varphi = M_.params(31);
M_.params(19) = 1.005;
piss = M_.params(19);
M_.params(36) = 8.9300;
sigmaS = M_.params(36);
M_.params(37) = 8.9367;
sigmaO = M_.params(37);
M_.params(34) = 15;
chi_s = M_.params(34);
M_.params(35) = 0.001;
chi_o = M_.params(35);
M_.params(40) = 0.05;
BDratio = M_.params(40);
M_.params(32) = 0.1;
tau0 = M_.params(32);
M_.params(28) = 0.2;
sig = M_.params(28);
M_.params(33) = 25;
y0 = M_.params(33);
M_.params(29) = 0.05;
theta1 = M_.params(29);
M_.params(30) = 2.6;
theta2 = M_.params(30);
M_.params(20) = 0.95;
rho_a = M_.params(20);
M_.params(21) = 0.95;
rho_g = M_.params(21);
M_.params(22) = 0.95;
rho_c = M_.params(22);
M_.params(23) = 0.95;
rho_m = M_.params(23);
M_.params(24) = 0.95;
rho_i = M_.params(24);
M_.params(25) = 0.40;
rho_r = M_.params(25);
M_.params(26) = 0.40;
rho_t = M_.params(26);
M_.params(27) = 0.90;
rho_p = M_.params(27);
M_.params(38) = 0.90;
rho_s = M_.params(38);
M_.params(39) = 0.90;
rho_o = M_.params(39);
resid;
estim_params_.var_exo = zeros(0, 10);
estim_params_.var_endo = zeros(0, 10);
estim_params_.corrx = zeros(0, 11);
estim_params_.corrn = zeros(0, 11);
estim_params_.param_vals = zeros(0, 10);
estim_params_.var_exo = [estim_params_.var_exo; 2, NaN, NaN, NaN, 4, .01, 2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 21, .92, NaN, NaN, 1, .5, 0.2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 8, NaN, NaN, NaN, 4, .01, 2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 27, .92, NaN, NaN, 1, .5, 0.2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 6, NaN, NaN, NaN, 4, .01, 2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 25, .5, NaN, NaN, 1, .5, 0.2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 3, NaN, NaN, NaN, 4, .01, 2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 22, .96, NaN, NaN, 1, .5, 0.2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 5, NaN, NaN, NaN, 4, .01, 2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 24, .9, NaN, NaN, 1, .5, 0.2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 4, NaN, NaN, NaN, 4, .01, 2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 23, .96, NaN, NaN, 1, .5, 0.2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 1, NaN, NaN, NaN, 4, .01, 2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 20, .9, NaN, NaN, 1, .5, 0.2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 7, NaN, NaN, NaN, 4, .01, 2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 26, .9, NaN, NaN, 1, .5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 15, .45, NaN, NaN, 1, .75, 0.1, NaN, NaN, NaN ];
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (1)^2;
M_.Sigma_e(4, 4) = (1)^2;
options_.irf = 30;
options_.order = 1;
var_list_ = {'y';'c_H';'c_E';'i';'pi';'r';'q';'e';'phi_E'};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'credit_NK_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'credit_NK_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'credit_NK_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'credit_NK_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'credit_NK_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'credit_NK_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'credit_NK_results.mat'], 'oo_recursive_', '-append');
end
disp('Note: 3 warning(s) encountered in the preprocessor')
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
